apiVersion: v2
name: monitoring
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
- name: prometheus
  version: "23.1.0"
  repository: "https://prometheus-community.github.io/helm-charts"
- name: grafana
  version: "6.58.4"
  repository: "https://grafana.github.io/helm-charts"