apiVersion: v2
name: sync
description: AFFiNE Sync Server
type: application
version: 0.0.0
appVersion: "0.11.0-canary.4"
dependencies:
  - name: gcloud-sql-proxy
    version: 0.0.0
    repository: "file://../gcloud-sql-proxy"
    condition: .global.database.gcloud.enabled
