[package]
edition = "2021"
name = "affine_native"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
affine_schema = { path = "./schema" }
anyhow = "1"
chrono = "0.4"
napi = { version = "2", default-features = false, features = [
  "napi5",
  "tokio_rt",
  "serde-json",
  "error_anyhow",
  "chrono_date",
] }
napi-derive = "2"
notify = { version = "6", features = ["serde"] }
once_cell = "1"
parking_lot = "0.12"
rand = "0.8"
serde = "1"
serde_json = "1"
sha3 = "0.10"
sqlx = { version = "0.7.4", default-features = false, features = [
  "sqlite",
  "migrate",
  "runtime-tokio",
  "tls-rustls",
  "chrono",
  "macros",
] }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1", default-features = false, features = [
  "serde",
  "v4",
  "fast-rng",
] }

[build-dependencies]
affine_schema = { path = "./schema" }
dotenv = "0.15"
napi-build = "2"
sqlx = { version = "0.7.4", default-features = false, features = [
  "sqlite",
  "runtime-tokio",
  "tls-rustls",
  "chrono",
  "macros",
  "migrate",
  "json",
] }
tokio = { version = "1", features = ["full"] }
