[package]
edition = "2021"
name    = "affine_server_native"
version = "1.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono       = { workspace = true }
file-format  = { workspace = true }
napi         = { workspace = true }
napi-derive  = { workspace = true }
rand         = { workspace = true }
sha3         = { workspace = true }
tiktoken-rs  = { workspace = true }
v_htmlescape = { workspace = true }
y-octo       = { workspace = true }

[target.'cfg(not(target_os = "linux"))'.dependencies]
mimalloc = { workspace = true }

[target.'cfg(all(target_os = "linux", not(target_arch = "arm")))'.dependencies]
mimalloc = { workspace = true, features = ["local_dynamic_tls"] }

[dev-dependencies]
tokio = "1"

[build-dependencies]
napi-build = { workspace = true }
