[package]
name = "affine_server_native"
version = "1.0.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4"
napi = { version = "2", default-features = false, features = [
  "napi5",
  "async",
] }
napi-derive = { version = "2", features = ["type-def"] }
rand = "0.8"
sha3 = "0.10"
y-octo = { git = "https://github.com/y-crdt/y-octo.git", branch = "main" }

[dev-dependencies]
tokio = "1"

[build-dependencies]
napi-build = "2"
