[package]
edition = "2021"
name = "affine_octobase"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1"
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2", default-features = false, features = [
  "napi4",
  "tokio_rt",
  "serde-json",
  "error_anyhow",
] }
napi-derive = "2"
notify = { version = "5", features = ["serde"] }
parking_lot = "0.12"
serde = "1"
serde_json = "1"
tokio = "1"
uuid = { version = "1", default-features = false, features = [
  "serde",
  "v4",
  "fast-rng",
] }

[build-dependencies]
napi-build = "2"
