name: standard check

on:
    push:
        branches: [ "develop", "master" ]
    pull_request:
        branches: [ "develop", "master" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
    main:
        name: Nx Cloud - Main Job
        uses: ./.github/workflows/nx-cloud-main.yml
        secrets: inherit
        with:
            main-branch-name: develop
            number-of-agents: 2
            parallel-commands: |
                pnpm exec nx-cloud record -- pnpm exec nx format:check
                pnpm e2e:ci ${{ github.ref == 'refs/heads/develop' && '--record' || '' }}
            parallel-commands-on-agents: |
                pnpm exec nx affected --target=lint --parallel=2 --exclude=components-common,keck,theme
                pnpm exec nx affected --target=build --parallel=2

    agents:
        name: Nx Cloud - Agents
        uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.6
        with:
            number-of-agents: 2
