name: Merge Check
on:
  merge_group:
    types: [checks_requested]

jobs:
  check_commit_run:
    name: Check commit run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const assert = (condition, message) => {
              if (!condition) {
                throw new Error(message)
              }
            }
            const { data } = await github.rest.checks.listSuitesForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: context.payload.merge_group.head_ref,
            })
            const names = data.check_runs.map((run) => run.name)
            assert(names.includes('E2E Test (1/4)'), 'E2E Test (1/4) not found')
            assert(names.includes('E2E Test (2/4)'), 'E2E Test (2/4) not found')
            assert(names.includes('E2E Test (3/4)'), 'E2E Test (3/4) not found')
            assert(names.includes('E2E Test (4/4)'), 'E2E Test (4/4) not found')
            assert(names.includes('Unit Test'), 'Unit Test not found')
