name: Publish Storybook

env:
  NODE_OPTIONS: --max-old-space-size=4096

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    paths-ignore:
      - README.md
      - .github/**
      - apps/server
      - apps/docs
      - apps/electron
      - '!.github/workflows/publish-storybook.yml'

jobs:
  publish-storybook:
    name: Publish Storybook
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          # This is required to fetch all commits for chromatic
          fetch-depth: 0
      - name: Setup Node.js
        uses: ./.github/actions/setup-node
        with:
          electron-install: false
      - name: Build Plugins
        run: yarn run build:plugins
      - uses: chromaui/action-next@v1
        with:
          workingDir: apps/storybook
          buildScriptName: build
          exitOnceUploaded: true
          onlyChanged: false
          diagnostics: true
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          NODE_OPTIONS: ${{ env.NODE_OPTIONS }}
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: chromatic-build-artifacts-${{ github.run_id }}
          path: |
            chromatic-diagnostics.json
            **/build-storybook.log
