replicaCount: 1
image:
  repository: ghcr.io/toeverything/affine-graphql
  pullPolicy: IfNotPresent
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
# map to NODE_ENV environment variable
env: 'production'
app:
  experimental:
    enableJwstCodec: true
  # AFFINE_SERVER_SUB_PATH
  path: ''
  # AFFINE_SERVER_HOST
  host: '0.0.0.0'
  doc:
    mergeInterval: "3000"
  jwt:
    secretName: jwt-private-key
    # base64 encoded ecdsa private key
    privateKey: ''
  objectStorage:
    r2:
      enabled: false
      secretName: r2
      accountId: ''
      accessKeyId: ''
      secretAccessKey: ''
      bucket: ''
  oauth:
    email:
      secretName: 'oauth-email'
      sender: 'noreply@toeverything.info'
      login: ''
      password: ''
      server: 'smtp.gmail.com'
      port: '465'
    google:
      enabled: false
      secretName: oauth-google
      clientId: ''
      clientSecret: ''
    github:
      enabled: false
      secretName: oauth-github
      clientId: ''
      clientSecret: ''

serviceAccount:
  create: true
  annotations: {}
  name: 'affine-graphql'

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

resources:
  limits:
    cpu: '4'
    memory: 8Gi
  requests:
    cpu: '2'
    memory: 4Gi

probe:
  initialDelaySeconds: 20

nodeSelector: {}
tolerations: []
affinity: {}
